### ISSUE TITLE
feature requests;

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#10]
1. dark [copy to clipboard] button in dark mode
<img width="522" alt="Ekran Resmi 2019-10-26 20 46 25" src="https://user-images.githubusercontent.com/36481442/67623813-520abf00-f832-11e9-8c05-e825f6b4f7e6.png">

2. optional [copy to clipboard] button
3. shorter app name (SourceCodeSyntaxHighlight.app)
4. When SourceCodeSyntaxHighlight.app is launched, the interface should appear immediately. `SyntaxHighlight > Preferences...` method is weird.
5. Disabling text selection in QuickLook window. Text selection prevents you from dragging the window in the middle.

**Comment by sbarex** [comment]
>     1. dark [copy to clipboard] button in dark mode
I have to do some checks

>     2. optional [copy to clipboard] button
On settings, uncheck `Show command toolbar`

>     3. shorter app name (SourceCodeSyntaxHighlight.app)
Yes... I need to find out how to set the name in the dock 

>     4. When SourceCodeSyntaxHighlight.app is launched, the interface should appear immediately. `SyntaxHighlight > Preferences...` method is weird.
Ok

>     5. Disabling text selection in QuickLook window. Text selection prevents you from dragging the window in the middle.
I have to do some checks

**Comment by hazarek** [comment]
For now, I removed the application because it consumes a lot of energy (macbook). and causes a slight delay when displaying the file. The application is not more ready. Thank you.

**Comment by sbarex** [comment]
Very strange. In my tests the xpc process takes up less than 15-20% of the processor for a few moments (less a second) and about 15 mb of memory, while the extension is about 3% of cpu. Furthermore, after a few seconds of inactivity, both processes are released. 
XCode indicates a zero energy impact.
For the display delay I must investigate. On my virtual machichine where I test the code don't show a very high delay. The time is caused to the initialization of the webview. I must try to check if defining the webview on the storyboard cause a fast initialization that create the view at runtime.

**Comment by hazarek** [comment]
Quick Look means QUICK look. it must be quick. Sublime Text opens files faster with highlight. when double click a source file.

**Comment by sbarex** [comment]
If in a virtual machine is reasonably quick I suppose that on a real machine is much fast.
This project is just a study. If you can contribute to improve it, I thank you,

**Comment by hazarek** [comment]
I don't judge you, I'm just giving feedback as an end user. The application can be optimized. Thanks for your effort.

**Comment by sbarex** [comment]
I have changed the connection with the XPC service. Now is not asynchronous. In this way the extension is more reactive.

**Comment by hazarek** [comment]
I'm gonna try tonight. If you don't mind, I will write my experience here.

**Comment by hazarek** [comment]
No delay. it's quick

- The change I made in the font window is not applied. sometimes applied. sometimes not (buggy)

- Preview disappears when you scroll after changing the file.
  -  ![bug1](https://user-images.githubusercontent.com/36481442/67642935-1f3ff400-f922-11e9-8990-1f0340513d75.gif)

- there is underlined links in highlights. and this is a side effect of text selection and links. i don't like underlined
  - ![drag](https://user-images.githubusercontent.com/36481442/67643001-f4a26b00-f922-11e9-91f7-7ce55ff4bfad.gif)

lastly, it would be nice if it supports markdown.
thank you.

**Comment by sbarex** [comment]
>     * The change I made in the font window is not applied. sometimes applied. sometimes not (buggy)
In my tests it never happened, can you give me more information?

>     * Preview disappears when you scroll after changing the file.
Ok, I hope is now corrected.

>     * There is underlined links in highlights. and this is a side effect of text selection and links. i don't like underlined. As I mentioned before. "Quick Look" should not allow text selection.

Oh, I didn't realize it! I saw that the `colorize.sh` script automatically activated a series of plugins to create links to the documentation of the functions of certain languages. I turned them off.

>     * "Preferences" window does not open when press "Quit" button and relaunch from dock. In my opinion, settings should be in the main window. Not in sub Preferences window.

For now I leave this behavior. The application also acts as a standalone viewer for source files and is useful for debugging. Maybe if there will be a final version I will fix this behavior.

> lastly, it would be nice if it supports markdown.

I have enabled the markdown format management. However we should not expect a real formatting of the file but rather the highlighting of the source code.
Probably is not the solution you would expect for this format.

> thank you.

**Comment by hazarek** [comment]
I upgraded to version 1.0b7. Great improvement in a short time thanks, We work well together.

1. I cannot reproduce the font bug. it's fixed.

2. The markdown change conflicted with the QLMarkdown I used. QLMarkdown is now ineffective. I didn't imagine the source code being highlighted instead of the actual formatting of the file. Sorry That's my fault, I want to use QLMarkdown again.

3. A new bug. The wrong mouse cursor icon appears for a while, Look carefully to cursor;  
  ![cursor2](https://user-images.githubusercontent.com/36481442/67701057-4c42e400-f9c0-11e9-8015-be0a0d1e5db4.gif)

  - when first opened
  ![cursor](https://user-images.githubusercontent.com/36481442/67701270-b78cb600-f9c0-11e9-8914-6726588e7729.gif)

thanks.

**Comment by hazarek** [comment]
look at second gif. When I watched the second gif animation I noticed. white file icon appears in miliseconds. quciklook seems unable to decide what to do.
![cursor-28 (sürüklenen)](https://user-images.githubusercontent.com/36481442/67705782-b19ad300-f9c8-11e9-8e27-715911171c5a.png)

**Comment by sbarex** [comment]
Ok, the cursor problem is fixed, and I removed the markdown support.
We should consider whether it is more efficient to use NSTextView or WKWebView. WebView is not intended for use as non interactive view. Also dragging the window by click in the middle of the view is not simple and for now I have used a not very elegant solution.

**Comment by hazarek** [comment]
The first GIF shown above has fixed. second GIF has partially fixed. The cursor icon appears for one second in the first preview. If the file loses focus it reappears on first boot. I'm not an apple developer. I'm just using Python for my design work. I am giving feedback only for hobby purposes.
thank you.
